version: "3.4"

services:

    client:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.prod
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - signal-server
        volumes:
            # https certificates
            - /root/certs/:/data/letsencrypt/
            - /etc/letsencrypt:/etc/letsencrypt/
           
    signal-server:
        container_name: 'signal-server'
        restart: unless-stopped
        build:
            context: ./signal
            dockerfile: Dockerfile.signal
            network: host
        ports:
            - "8000:8000"
